name: SMS Notification
on:
  push:
    branches:
      - main

jobs:
  send_sms:
    runs-on: ubuntu-latest
    steps:
      - name: Set up ssmtp
        run: |
          sudo apt-get -y install ssmtp
          echo "root=postmaster\nmailhub=smtp.gmail.com:587\nAuthUser=mary.s.maksemos.com\nAuthPass=<your-email-password>\nUseSTARTTLS=YES" | sudo tee /etc/ssmtp/ssmtp.conf
          sudo chmod 640 /etc/ssmtp/ssmtp.conf
          sudo chown root:mail /etc/ssmtp/ssmtp.conf

      - name: Send SMS notification
        run: |
          echo "Pipeline Notification: Repository - Branch - Commit" | ssmtp 0737796897@sms.comviq.se
